### ISSUE TITLE
偶现的异常：width and height must be > 0

### ISSUE THREAD

**Issue by qingtiandashen** [goweii/StatusBarCompat#1]
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/5088785/225871482-6d9b43e1-443d-4ef6-bce9-407a61f46166.png">

不知道有没有遇到过这个崩溃问题

**Comment by goweii** [comment]
这个库好久都没维护了，动态模式这个还有性能问题。
你要是继续用的话我周末在维护一版。

**Comment by goweii** [comment]
试下1.3.0版本
